### ISSUE TITLE
OCE keyword intermittent in PGF

### ISSUE THREAD

**Issue by KamboRambo** [0xbs/premade-regions#7]
Using regions 2.0.1 and PGF 3.4.1 on game version 10.0.2

OCE tag works fine in main window, but is only partially working or intermittent within PGF. Other region tags appear fine or is just not apparent. Not sure if an issue with PGF or this addon

Within PGF
![image](https://user-images.githubusercontent.com/44149793/210191983-30482812-cc47-4f85-8eab-eb9202b2ca9a.png)

In main window (OCE text search)

![image](https://user-images.githubusercontent.com/44149793/210191999-10d9a1dd-bacb-448c-8bd2-7fb22b058151.png)

**Comment by 0xbs** [comment]
You are applying two very different filters:

1. Typing "oce" into the search box runs a search on the server for all groups that have "oce" in the name. All 50 search results returned from the server are groups that match this filter. If a player is playing on OCE but did not put "oce" in the title, you won't see the group.
2. Typing "oce" into the expression field first waits for 50 search results (usually random except if you enter something in the search box) to be returned from the server. It then removes all search results where the realm of the group leader is not an OCE realm. Leader realm is determined by the name suffix of the leader. On very new groups, the leader name is not yet available, these groups are removed as well. This leads to very few groups but includes groups without oce in the description.

If players are consistently writing "oce" into the title, stick with method 1. Otherwise experiment with method 2. For US players, typing `not oce` in to the PGF expression box returns the inverse set, hence sometimes includes some very new OCE groups when the leader name was delayed.

So I conclude that there is not really a bug, but also no perfect solution to your problem. Blizzard should just set up OCE servers for you guys or give you a filter in the options dropdown…
